const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=960,H=600, keys={}; let last=0, elapsed=0, paused=false, wave=1, waveActive=false, waveTotal=0, spawned=0, spawnClock=0, kills=0, level=1, xp=0, xpNeed=100, auto=false, intermission=false, special=false, toastTimer=0;
const player={x:W/2,y:H/2,r:13,hp:100,maxHp:100,speed:210,regen:3,lastHit:-99};
let enemies=[],shots=[],enemyShots=[],pickups=[],particles=[],weapons={bow:{name:'LONGBOW',level:1,damage:2,rate:2,color:'#55e6ff'}};
const defs={square:{hp:3,speed:38,r:15,color:'#ff6689',sides:4,weight:1},triangle:{hp:1,speed:72,r:13,color:'#ffc857',sides:3,weight:1},hex:{hp:5,speed:27,r:18,color:'#a778ff',sides:6,weight:1},trap:{hp:8,speed:18,r:22,color:'#ff965d',sides:4,weight:1},bowtie:{hp:4,speed:25,r:18,color:'#70d6c1',sides:4,weight:1}};
const choices=[{id:'bow',title:'TUNED STRING',desc:'Longbow fires 22% faster.',kind:'weapon'},{id:'laser',title:'PRISM LASER',desc:'Unlocks a piercing beam that auto-targets.',kind:'new'},{id:'bomb',title:'VOID CHARGE',desc:'Unlocks orbiting bombs that detonate.',kind:'new'},{id:'sword',title:'STAR BLADE',desc:'Unlocks a close-range rotating blade.',kind:'new'},{id:'heart',title:'REINFORCED HULL',desc:'Increase max hull by 25 and repair fully.',kind:'support'},{id:'boots',title:'RUNNING SHOES',desc:'Movement speed increased by 18%.',kind:'support'},{id:'regen',title:'NANITE REPAIR',desc:'Hull regeneration increased by 2 / sec.',kind:'support'},{id:'damage',title:'HOTTER CORES',desc:'All weapon damage increased by 18%.',kind:'support'},{id:'tempo',title:'QUICK CIRCUIT',desc:'All weapon attack speed increased by 14%.',kind:'support'}];
function resize(){const d=devicePixelRatio||1;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0)}resize();addEventListener('resize',resize);addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' '){e.preventDefault();togglePause()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.getElementById('pauseBtn').onclick=togglePause;document.getElementById('autoContinue').onchange=e=>auto=e.target.checked;
function togglePause(){if(!intermission&&!special){paused=!paused;if(paused)showPause();else hideOverlay()}}
function rand(a,b){return a+Math.random()*(b-a)} function edge(){let s=Math.floor(Math.random()*4);return s===0?{x:rand(0,W),y:-30}:s===1?{x:W+30,y:rand(0,H)}:s===2?{x:rand(0,W),y:H+30}:{x:-30,y:rand(0,H)}}
function pickType(){let pool=['square','square','triangle'];if(wave>=3)pool.push('hex');if(wave>=6)pool.push('trap');if(wave>=8)pool.push('bowtie');return pool[Math.floor(Math.random()*pool.length)]}
function startWave(){waveActive=true;intermission=false;waveTotal=6+wave*3;spawned=waveTotal;spawnClock=0;for(let i=0;i<Math.min(3,waveTotal);i++){spawnEnemy();spawned--}document.getElementById('waveState').textContent='INCOMING';hud()}
function nextWave(){wave++;document.getElementById('waveNumber').textContent=wave;document.getElementById('bestWave').textContent=Math.max(wave,+document.getElementById('bestWave').textContent);if(wave%10===0){special=true;specialModal()}else startWave()}
function spawnEnemy(){let type=pickType(),d=defs[type],p=edge();enemies.push({type,x:p.x,y:p.y,hp:d.hp,maxHp:d.hp,r:d.r,phase:Math.random()*9,shoot:type==='bowtie'?rand(2,4):99})}
function nearest(x,y){return enemies.reduce((best,e)=>!best||Math.hypot(e.x-x,e.y-y)<Math.hypot(best.x-x,best.y-y)?e:best,null)}
function fire(){let e=nearest(player.x,player.y);if(!e)return;let a=Math.atan2(e.y-player.y,e.x-player.x), speed=450;shots.push({x:player.x,y:player.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:4,damage:weapons.bow.damage,life:2,color:'#b4f4ff'});burst(player.x+Math.cos(a)*12,player.y+Math.sin(a)*12,'#55e6ff',3)}
function update(dt){elapsed+=dt;if(waveActive&&spawned>0){spawnClock+=dt*(1.6+wave*.07);while(spawnClock>=1&&spawned>0){spawnClock--;spawned--;spawnEnemy()}}if(waveActive&&!enemies.length&&spawned<=0){waveActive=false;intermission=true;document.getElementById('waveState').textContent='CLEAR';if(wave%10===0){special=true;specialModal()}else intermissionModal()}
 let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),len=Math.hypot(dx,dy)||1;player.x=Math.max(24,Math.min(W-24,player.x+dx/len*player.speed*dt));player.y=Math.max(32,Math.min(H-28,player.y+dy/len*player.speed*dt));if(elapsed-player.lastHit>3)player.hp=Math.min(player.maxHp,player.hp+player.regen*dt);
 if(Math.floor(elapsed/2)>Math.floor((elapsed-dt)/2))fire();if(weapons.laser&&Math.floor(elapsed*weapons.laser.rate)>Math.floor((elapsed-dt)*weapons.laser.rate)){let e=nearest(player.x,player.y);if(e){e.hp-=weapons.laser.damage;burst(e.x,e.y,weapons.laser.color,5)}}if(weapons.bomb&&Math.floor(elapsed*weapons.bomb.rate)>Math.floor((elapsed-dt)*weapons.bomb.rate)){let e=nearest(player.x,player.y);if(e){for(let v of enemies)if(Math.hypot(v.x-e.x,v.y-e.y)<72)v.hp-=weapons.bomb.damage;burst(e.x,e.y,weapons.bomb.color,18)}}if(weapons.sword){let a=elapsed*2.5, sx=player.x+Math.cos(a)*45, sy=player.y+Math.sin(a)*45;for(let e of enemies)if(Math.hypot(e.x-sx,e.y-sy)<e.r+10)e.hp-=weapons.sword.damage*dt}for(let e of enemies){let a=Math.atan2(player.y-e.y,player.x-e.x), wig=e.type==='bowtie'?Math.sin(elapsed*4+e.phase)*.8:0;e.x+=Math.cos(a+wig)*defs[e.type].speed*dt;e.y+=Math.sin(a+wig)*defs[e.type].speed*dt;e.shoot-=dt;if(e.type==='bowtie'&&e.shoot<=0){e.shoot=rand(2.5,4);let aa=Math.atan2(player.y-e.y,player.x-e.x);enemyShots.push({x:e.x,y:e.y,vx:Math.cos(aa)*150,vy:Math.sin(aa)*150,r:5})}if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+player.r){player.hp-=10*dt;player.lastHit=elapsed}}
 for(let s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let e of enemies)if(Math.hypot(s.x-e.x,s.y-e.y)<s.r+e.r){e.hp-=s.damage;s.life=0;burst(e.x,e.y,s.color||'#fff',4)}}shots=shots.filter(s=>s.life>0&&s.x>-20&&s.x<W+20&&s.y>-20&&s.y<H+20);for(let s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;if(Math.hypot(s.x-player.x,s.y-player.y)<s.r+player.r){player.hp-=8;player.lastHit=elapsed;s.x=-100}}enemyShots=enemyShots.filter(s=>s.x>-20&&s.x<W+20&&s.y>-20&&s.y<H+20);for(let p of pickups){p.y+=Math.sin(elapsed*4+p.seed)*.15;p.x+=(player.x-p.x)*dt*1.7;p.y+=(player.y-p.y)*dt*1.7;if(Math.hypot(p.x-player.x,p.y-player.y)<22){xp+=p.value;p.dead=true;burst(p.x,p.y,'#ffe17a',8);checkXp()}}pickups=pickups.filter(p=>!p.dead);let dead=[];enemies=enemies.filter(e=>{if(e.hp<=0){dead.push(e);return false}return true});dead.forEach(e=>{kills++;pickups.push({x:e.x,y:e.y,value:e.type==='trap'?4:2,seed:Math.random()});burst(e.x,e.y,defs[e.type].color,10)});for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);if(player.hp<=0)gameOver();hud()}
function checkXp(){if(xp>=xpNeed){xp-=xpNeed;xpNeed=Math.floor(xpNeed*1.22);level++;paused=true;upgradeModal()}}
function burst(x,y,color,n){for(let i=0;i<n;i++){let a=Math.random()*6.28;particles.push({x,y,vx:Math.cos(a)*rand(20,80),vy:Math.sin(a)*rand(20,80),life:rand(.25,.6),color})}}
function poly(x,y,r,sides,rot=0){ctx.beginPath();for(let i=0;i<sides;i++){let a=rot+i*Math.PI*2/sides;ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r)}ctx.closePath()}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#090f1b';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#17243a';ctx.lineWidth=1;for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='#263b56';ctx.strokeRect(18,31,W-36,H-55);for(let p of pickups){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(elapsed);ctx.fillStyle='#ffe17a';ctx.shadowBlur=16;ctx.shadowColor='#ffe17a';poly(0,0,8,5,-Math.PI/2);ctx.fill();ctx.restore()}for(let e of enemies){let d=defs[e.type];ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=d.color;ctx.shadowBlur=15;ctx.shadowColor=d.color;if(e.type==='bowtie'){ctx.rotate(Math.PI/4);ctx.fillRect(-15,-4,30,8);ctx.fillRect(-4,-15,8,30)}else{poly(0,0,d.r,d.sides,e.type==='triangle'?Math.PI/2:Math.PI/4);ctx.fill()}ctx.restore();if(e.hp<e.maxHp){ctx.fillStyle='#222b3e';ctx.fillRect(e.x-15,e.y-e.r-8,30,3);ctx.fillStyle=d.color;ctx.fillRect(e.x-15,e.y-e.r-8,30*(e.hp/e.maxHp),3)}}for(let s of shots){ctx.fillStyle=s.color;ctx.shadowBlur=12;ctx.shadowColor=s.color;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill();ctx.shadowBlur=0}for(let s of enemyShots){ctx.fillStyle='#ff708e';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()}for(let p of particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);ctx.globalAlpha=1}ctx.save();ctx.translate(player.x,player.y);ctx.fillStyle='#eaf7ff';ctx.shadowBlur=24;ctx.shadowColor='#55e6ff';ctx.beginPath();ctx.arc(0,0,player.r,0,7);ctx.fill();ctx.strokeStyle='#55e6ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,player.r+5,-Math.PI/2,-Math.PI/2+Math.PI*2*(player.hp/player.maxHp));ctx.stroke();ctx.restore()}
function hud(){document.getElementById('healthFill').style.width=Math.max(0,player.hp/player.maxHp*100)+'%';document.getElementById('healthText').textContent=Math.ceil(player.hp)+' / '+player.maxHp;document.getElementById('xpFill').style.width=xp/xpNeed*100+'%';document.getElementById('xpText').textContent=xp+' / '+xpNeed+' XP';document.getElementById('levelText').textContent='LV '+level;document.getElementById('killCount').textContent=kills;document.getElementById('timer').textContent=new Date(elapsed*1000).toISOString().slice(14,19);document.getElementById('weaponList').innerHTML=Object.values(weapons).map(w=>`<span class="weapon-item"><i class="weapon-dot" style="background:${w.color}"></i>${w.name} <small>★${w.level}</small></span>`).join('')}
function modal(html){const o=document.getElementById('overlay');o.innerHTML=html;o.classList.remove('hidden')};function hideOverlay(){document.getElementById('overlay').classList.add('hidden')}
function upgradeModal(){let opts=[...choices].sort(()=>Math.random()-.5).slice(0,3);modal(`<div class="modal"><div class="eyebrow">ASCENSION REACHED // LEVEL ${level}</div><h2>Choose your evolution</h2><p>The arena is paused. Install one upgrade to continue your run.</p><div class="cards">${opts.map((o,i)=>`<div class="card"><span class="card-key">0${i+1} // ${o.kind.toUpperCase()}</span><h3>${o.title}</h3><p>${o.desc}</p><button data-id="${o.id}">INSTALL</button></div>`).join('')}</div></div>`);document.querySelectorAll('.card button').forEach(b=>b.onclick=()=>apply(b.dataset.id))}
function apply(id){let o=choices.find(x=>x.id===id);if(id==='bow'){weapons.bow.level++;weapons.bow.damage+=1}else if(['laser','bomb','sword'].includes(id)){if(!weapons[id])weapons[id]={name:id==='laser'?'PRISM LASER':id==='bomb'?'VOID CHARGE':'STAR BLADE',level:1,damage:3,rate:4,color:id==='laser'?'#c879ff':id==='bomb'?'#ff965d':'#ffe17a'}}else if(id==='heart'){player.maxHp+=25;player.hp=player.maxHp}else if(id==='boots')player.speed*=1.18;else if(id==='regen')player.regen+=2;else if(id==='damage')Object.values(weapons).forEach(w=>w.damage*=1.18);else if(id==='tempo')Object.values(weapons).forEach(w=>w.rate*=1.14);hideOverlay();paused=false;notify(o.title+' INSTALLED')}
function intermissionModal(){if(auto){setTimeout(()=>{if(intermission){hideOverlay();startWave()}},700);return}modal(`<div class="modal"><div class="eyebrow">SECTOR CLEAR</div><h2>Wave ${wave} survived</h2><p>Systems cooling. Collect your bearings before the next swarm.</p><button class="continue" id="continue">BEGIN WAVE ${wave+1} →</button></div>`);document.getElementById('continue').onclick=()=>{hideOverlay();nextWave()}}
function specialModal(){modal(`<div class="modal"><div class="eyebrow">MILESTONE RELIC // WAVE ${wave}</div><h2>Choose a relic</h2><p>A permanent anomaly has surfaced. Its power lasts for the rest of this run.</p><div class="cards"><div class="card"><span class="card-key">RELIC 01</span><h3 class="accent">OVERDRIVE HEART</h3><p>Double attack speed and +40 max hull.</p><button data-relic="over">CLAIM RELIC</button></div><div class="card"><span class="card-key">RELIC 02</span><h3 class="accent">ORBITAL CROWN</h3><p>Three stars orbit you, damaging anything they touch.</p><button data-relic="orbit">CLAIM RELIC</button></div><div class="card"><span class="card-key">RELIC 03</span><h3 class="accent">PHOENIX CODE</h3><p>Recover 50% hull after every tenth wave.</p><button data-relic="phoenix">CLAIM RELIC</button></div></div></div>`);document.querySelectorAll('[data-relic]').forEach(b=>b.onclick=()=>{if(b.dataset.relic==='over'){player.maxHp+=40;Object.values(weapons).forEach(w=>w.rate*=2)}if(b.dataset.relic==='orbit')weapons.orbit={name:'ORBITAL CROWN',level:1,damage:2,rate:1,color:'#ffe17a'}if(b.dataset.relic==='phoenix')player.hp=player.maxHp;special=false;hideOverlay();startWave()})}
function showPause(){modal(`<div class="modal"><div class="eyebrow">SYSTEM PAUSED</div><h2>Hold the line.</h2><p>Press SPACE or the pause control to return to the arena.</p><button class="continue" id="resume">RESUME RUN</button></div>`);document.getElementById('resume').onclick=()=>{hideOverlay();paused=false}}
function gameOver(){paused=true;modal(`<div class="modal"><div class="eyebrow">SIGNAL LOST</div><h2>Run terminated.</h2><p>You reached wave ${wave} and cleared ${kills} hostiles.</p><button class="continue" id="restart">REBOOT RUN</button></div>`);document.getElementById('restart').onclick=()=>location.reload()}
function notify(t){let el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function drawWeaponGuide(){let e=nearest(player.x,player.y);if(e){let a=Math.atan2(e.y-player.y,e.x-player.x);ctx.save();ctx.translate(player.x,player.y);ctx.rotate(a);ctx.strokeStyle='#55e6ff';ctx.globalAlpha=.8;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(5,0);ctx.lineTo(29,0);ctx.stroke();ctx.strokeStyle='#b4f4ff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(13,-8);ctx.quadraticCurveTo(25,0,13,8);ctx.stroke();ctx.restore()}if(weapons.sword){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(elapsed*2.5);ctx.strokeStyle='#ffe17a';ctx.shadowBlur=12;ctx.shadowColor='#ffe17a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(27,0);ctx.lineTo(56,0);ctx.stroke();ctx.restore()}if(weapons.bomb){ctx.strokeStyle='#ff965d';ctx.globalAlpha=.5;ctx.setLineDash([4,5]);ctx.beginPath();ctx.arc(player.x,player.y,72,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(!paused){update(dt)}draw();drawWeaponGuide();requestAnimationFrame(loop)}startWave();requestAnimationFrame(loop);
